
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: BalleCofe
    networks:
      - app-network

  frontend:
    build:
      context: ./vite-project
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: BalleCofe
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
